# Generated by Django 6.0 on 2026-01-07 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='mob',
        ),
    ]
