# Generated by Django 6.0 on 2026-02-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='author',
            new_name='bloger',
        ),
    ]
