# Generated by Django 6.0 on 2026-01-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
