# Generated by Django 6.0 on 2026-01-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='jobrole',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
