# Generated by Django 6.0 on 2026-02-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='banner',
            field=models.ImageField(blank=True, default='1234.jpg', upload_to=''),
        ),
    ]
