# Generated by Django 6.0 on 2026-02-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0002_alter_articlemodel_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
